#### HT001: Use one command to import data from a CSV file, `HT001a.csv`, using the first row as column labels, and the first column as row labels. Name the data imported as `data`.

In [1]:
# slide 169
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
data

b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2

In [2]:
# slide 171
# What if the file is newfolder\newfile.csv?
# Windows (1)
data=pd.read_csv('newfolder\\newfile.csv')
data

a  b  c  d  e
0  0  1  2  3  4
1  1  5  6  7  8
2  2  9  8  7  6
3  3  5  4  3  2

In [3]:
# slide 171
# What if the file is newfolder\newfile.csv?
# Windows (2)
data=pd.read_csv(r'newfolder\newfile.csv')
data

a  b  c  d  e
0  0  1  2  3  4
1  1  5  6  7  8
2  2  9  8  7  6
3  3  5  4  3  2

In [4]:
# slide 173
# What if the labels are as in HT001b.csv?
data=pd.read_csv('HT001b.csv', index_col=0, header=0)
data

b  a.1  d e  1
a                
2  1    2    3  4
4  5    6    7  8
3  9    8    7  6
4  5    4    3  2

In [5]:
# slide 174 (1)
data.columns

Index(['b', 'a.1', 'd e', '1'], dtype='object')

In [6]:
# slide 174 (2)
data.index

Int64Index([2, 4, 3, 4], dtype='int64', name='a')

#### HT002: Use an appropriate position-based indexing/slicing method to select data in `data`.

In [7]:
# slide 175
# position-based indexing 
data.iloc[0,0]

1

In [8]:
# slide 177
# position-based slicing (1)
data.iloc[0:2,0:2]

b  a.1
a        
2  1    2
4  5    6

In [9]:
# slide 179
# position-based slicing (2)
# the 1st row
data.iloc[0,:]

b      1
a.1    2
d e    3
1      4
Name: 2, dtype: int64

In [10]:
# slide 181
# position-based slicing (3)
# the 1st column
data.iloc[:,0]

a
2    1
4    5
3    9
4    5
Name: b, dtype: int64

In [11]:
# slide 183
# DataFrame => Numpy 2D ndarray
data.values

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6],
       [5, 4, 3, 2]], dtype=int64)

In [12]:
# slide 185
# position-based fancy indexing
data.iloc[[2,0],[0,1]]

b  a.1
a        
3  9    8
2  1    2

## HT003: Use an appropriate label-based indexing/slicing method to select data in `data`.

In [13]:
# slide 187
# label-based indexing
print(data.loc[2,'b'])
print(data['b'][2])

1
1


In [14]:
# slide 189
# label-based slicing (1)
data.loc[2:3,'b':'1']

b  a.1  d e  1
a                
2  1    2    3  4
4  5    6    7  8
3  9    8    7  6

In [15]:
# slide 190
# label-based slicing (2): row with label 2
data.loc[2,:]

b      1
a.1    2
d e    3
1      4
Name: 2, dtype: int64

In [16]:
# slide 192
# label-based slicing (3): column with label a.1
data.loc[:,'a.1']

a
2    2
4    6
3    8
4    4
Name: a.1, dtype: int64

In [17]:
# slide 194
# label-based fancy indexing
data.loc[[2,3],['b','1']]

b  1
a      
2  1  4
3  9  6

## HT004: Add a column to `data`.

In [18]:
# slide 196
data=pd.read_csv('HT001b.csv', index_col=0, header=0)
data

b  a.1  d e  1
a                
2  1    2    3  4
4  5    6    7  8
3  9    8    7  6
4  5    4    3  2

In [19]:
# slide 196 (1)
data=pd.read_csv('HT001b.csv', index_col=0, header=0)
# add a column (1): a number
data['f1']=1
#data.loc[:,'f1']=1
data

b  a.1  d e  1  f1
a                    
2  1    2    3  4   1
4  5    6    7  8   1
3  9    8    7  6   1
4  5    4    3  2   1

In [20]:
# slide 196 (2)
data=pd.read_csv('HT001b.csv', index_col=0, header=0)
data['f1']=1
#data.loc[:,'f1']=1
# add a column (2): an iterable
data['f2']=range(4)
#data['f2']=[0,1,2,3]
#data['f2']=[[0],[1],[2],[3]]
#data['f2']=[[0,1,2,3]] #Wrong
#data.loc[:,'f2']=range(4)
#data.loc[:,'f2']=[0,1,2,3]
#data.loc[:,'f2']=[[0],[1],[2],[3]]
#data.loc[:,'f2']=[[0,1,2,3]] #Wrong
data

b  a.1  d e  1  f1  f2
a                        
2  1    2    3  4   1   0
4  5    6    7  8   1   1
3  9    8    7  6   1   2
4  5    4    3  2   1   3

In [21]:
# slide 197 (1)
# add a column (3): a Numpy array
import numpy as np
np.arange(4)

array([0, 1, 2, 3])

In [22]:
np.arange(4).reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [23]:
np.arange(4).reshape(1,4)

array([[0, 1, 2, 3]])

In [24]:
# slide 197 (2)
data=pd.read_csv('HT001b.csv', index_col=0, header=0)
data['f1']=1
data['f2']=range(4)
#
data['f3']=np.arange(4)
#data['f3']=np.arange(4).reshape(4,1)
#data['f3']=np.arange(4).reshape(1,4) #Wrong
data

b  a.1  d e  1  f1  f2  f3
a                            
2  1    2    3  4   1   0   0
4  5    6    7  8   1   1   1
3  9    8    7  6   1   2   2
4  5    4    3  2   1   3   3

In [25]:
# slide 198 (1)
# add a column (4): a Series (with different labels)
pd.Series(range(4))

0    0
1    1
2    2
3    3
dtype: int64

In [26]:
# slide 198 (2)
data=pd.read_csv('HT001b.csv', index_col=0, header=0)
data['f1']=1
data['f2']=range(4)
data['f3']=np.arange(4)
#
#data['f4']=pd.Series(range(3))
data['f4']=pd.Series(range(4))
#data['f4']=pd.Series(range(5))
#data.loc[:,'f4']=pd.Series(range(3))
#data.loc[:,'f4']=pd.Series(range(4))
#data.loc[:,'f4']=pd.Series(range(5))
data

b  a.1  d e  1  f1  f2  f3   f4
a                                 
2  1    2    3  4   1   0   0  2.0
4  5    6    7  8   1   1   1  NaN
3  9    8    7  6   1   2   2  3.0
4  5    4    3  2   1   3   3  NaN

In [27]:
# slide 199 (1)
# add a column (5): a DataFrame
pd.DataFrame([[i] for i in range(4)])

0
0  0
1  1
2  2
3  3

In [28]:
pd.DataFrame([[i for i in range(4)]], index=[2])

0  1  2  3
2  0  1  2  3

In [29]:
# slide 199 (2)
data=pd.read_csv('HT001b.csv', index_col=0, header=0)
data['f1']=1
data['f2']=range(4)
data['f3']=np.arange(4)
data['f4']=pd.Series(range(4))
#
#data['f5']=pd.DataFrame([[i] for i in range(3)])
data['f5']=pd.DataFrame([[i] for i in range(4)])
#data['f5']=pd.DataFrame([[i] for i in range(5)])
#data['f5']=pd.DataFrame([[i for i in range(4)]],index=[2]) #Wrong
data

b  a.1  d e  1  f1  f2  f3   f4   f5
a                                      
2  1    2    3  4   1   0   0  2.0  2.0
4  5    6    7  8   1   1   1  NaN  NaN
3  9    8    7  6   1   2   2  3.0  3.0
4  5    4    3  2   1   3   3  NaN  NaN

In [30]:
# slide 200
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
# Homework: Use one command to add a column to data, 
# using the first row of data, and name this column f.
#<Test Your Answer>

#
data

b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2

## HT005: Add a row to `data`.

In [31]:
# slide 206
%reset -f
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
# data.loc[rowname,:]=...
data.loc[100,:]=1
#data.loc[100,:]=[1]
#data.loc[100,:]=[[1]] #Wrong
#data.loc[100,:]=np.array(1)
#data.loc[100,:]=np.array([1])
#data.loc[100,:]=np.array([[1]])
data

b    c    d    e
a                      
0    1.0  2.0  3.0  4.0
1    5.0  6.0  7.0  8.0
2    9.0  8.0  7.0  6.0
3    5.0  4.0  3.0  2.0
100  1.0  1.0  1.0  1.0

In [32]:
# slide 207
%reset -f
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
# data.loc[colname,:]=...
data.loc[100,:]=range(1,5)
#data.loc[100,:]=[1,2,3,4]
#data.loc[100,:]=[[1,2,3,4]] #Wrong
#data.loc[100,:]=[[1],[2],[3],[4]] #Wrong
#data.loc[100,:]=np.array([1,2,3,4])
#data.loc[100,:]=np.array([[1,2,3,4]])
#data.loc[100,:]=np.array([[1],[2],[3],[4]]) #Wrong
data

b    c    d    e
a                      
0    1.0  2.0  3.0  4.0
1    5.0  6.0  7.0  8.0
2    9.0  8.0  7.0  6.0
3    5.0  4.0  3.0  2.0
100  1.0  2.0  3.0  4.0

In [33]:
# slide 209
# a dictionary
%reset -f
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
#data=data.append({k:1 for (v,k) in enumerate(data.columns,1)},ignore_index=True)
data=data.append({k:v for (v,k) in enumerate(data.columns,1)},ignore_index=True)
data

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


b  c  d  e
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
4  1  2  3  4

In [34]:
# slide 210
# Error: a dictionary + "ignore_index=False"
%reset -f
#import pandas as pd
#data=pd.read_csv('HT001a.csv', index_col=0, header=0)
#data=data.append({k:1 for (v,k) in enumerate(data.columns,1)})
#data=data.append({k:v for (v,k) in enumerate(data.columns,1)})
#data

In [35]:
# slide 211
# a list of dictionaries
%reset -f
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
#data=data.append([{k:1 for (v,k) in enumerate(data.columns,1)}])
#data=data.append([{k:1 for (v,k) in enumerate(data.columns,1)}], ignore_index=True)
data=data.append([{k:v for (v,k) in enumerate(data.columns,1)}])
#data=data.append([{k:v for (v,k) in enumerate(data.columns,1)}], ignore_index=True)
data

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


b  c  d  e
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
0  1  2  3  4

In [36]:
# slide 212
# a Series
%reset -f
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
#data=data.append(pd.Series(1, index=data.columns),
#data=data.append(pd.Series([1,2,3,4], index=data.columns),
data=data.append(pd.Series(range(1,5), index=data.columns),
                                        ignore_index=True)
data

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


b  c  d  e
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
4  1  2  3  4

In [37]:
# slide 213
# a list of Serieses
%reset -f
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
#data=data.append([pd.Series(1, index=data.columns)])
#data=data.append([pd.Series([1,2,3,4], index=data.columns)])
data=data.append([pd.Series(range(1,5), index=data.columns)])
data

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


b  c  d  e
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
0  1  2  3  4

In [38]:
# slide 214
# a DataFrame
%reset -f
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
#data=data.append(pd.DataFrame(1, 
#data=data.append(pd.DataFrame([[i for i in range(1,5)]], 
data=data.append(pd.DataFrame(np.arange(1,5).reshape(1,4), 
                              columns=data.columns,
                              index=[100]))
data

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


b  c  d  e
0    1  2  3  4
1    5  6  7  8
2    9  8  7  6
3    5  4  3  2
100  1  2  3  4

## HT006: Delete a row/column in `data`.

In [39]:
# slide 217
%reset -f
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
del data['b'] #or del data[data.columns[0]]
print(data)
data.drop('c', axis=1, inplace=True)
print(data)
data.drop(data.columns[0], axis=1, inplace=True)
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   c  d  e
a         
0  2  3  4
1  6  7  8
2  8  7  6
3  4  3  2
   d  e
a      
0  3  4
1  7  8
2  7  6
3  3  2
   e
a   
0  4
1  8
2  6
3  2


In [40]:
# slide 219
%reset -f
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.drop(0, inplace=True)
print(data)
data.drop(data.index[0], inplace=True)
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
2  9  8  7  6
3  5  4  3  2


## How to swap two values in variables `a` and `b`

In [41]:
# slide 223
a=1
b=2
a=b
b=a
a,b

(2, 2)

In [42]:
# slide 224
a=1
b=2
temp=a
a=b
b=temp
a,b

(2, 1)

In [43]:
# slide 225
a=1
b=2
a, b=b, a
a,b

(2, 1)

## HT007: Swap two rows/columns in `data`

In [44]:
# slide 227
# A wrong answer to swap two columns
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
temp=data['b']
data['b']=data['c']
data['c']=temp
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  2  2  3  4
1  6  6  7  8
2  8  8  7  6
3  4  4  3  2


In [45]:
# slide 228
# Another wrong answer to swap to columns
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data['b'], data['c']=data['c'], data['b']
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  2  2  3  4
1  6  6  7  8
2  8  8  7  6
3  4  4  3  2


In [46]:
# slide 229
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
temp=data['b']
temp[0]=100
data

b  c  d  e
a              
0  100  2  3  4
1    5  6  7  8
2    9  8  7  6
3    5  4  3  2

In [47]:
# slide 230 (1)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
temp=data['b']
data['b']=data['c']
data

b  c  d  e
a            
0  2  2  3  4
1  6  6  7  8
2  8  8  7  6
3  4  4  3  2

In [48]:
# slide 230 (2)
temp

a
0    2
1    6
2    8
3    4
Name: b, dtype: int64

In [49]:
# slide 232 (1)
data=[[1,2],[3,4]]
print(data)
data[0]=data[1]
print(data)
data[0][0]=100
print(data)

[[1, 2], [3, 4]]
[[3, 4], [3, 4]]
[[100, 4], [100, 4]]


In [50]:
# slide 232 (2)
import numpy as np
x=[[1,2],[3,4]]
data=np.array(x)
print(data)
data[0]=data[1]
print(data)
data[0][0]=100
print(data)

[[1 2]
 [3 4]]
[[3 4]
 [3 4]]
[[100   4]
 [  3   4]]


In [51]:
# slide 232 (3)
import pandas as pd
x=[[1,2],[3,4]]
data=pd.DataFrame(x)
print(data)
data.iloc[0]=data.iloc[1]
print(data)
data.iloc[0][0]=100
print(data)

   0  1
0  1  2
1  3  4
   0  1
0  3  4
1  3  4
     0  1
0  100  4
1    3  4


In [52]:
# A wrong attempt: Numpy swap two rows
import numpy as np
x=[[1,2],[3,4]]
data=np.array(x)
print(data)
temp=data[0]
data[0]=data[1]
data[1]=temp
print(data)

[[1 2]
 [3 4]]
[[3 4]
 [3 4]]


In [53]:
# Numpy swap two rows
import numpy as np
x=[[1,2],[3,4]]
data=np.array(x)
print(data)
temp=data[0].copy()
data[0]=data[1]
data[1]=temp
print(data)

[[1 2]
 [3 4]]
[[3 4]
 [1 2]]


In [54]:
# slide 233 (1)
# swap two columns (1)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
temp=data['b'].copy()
data['b']=data['c']
data['c']=temp
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  2  1  3  4
1  6  5  7  8
2  8  9  7  6
3  4  5  3  2


In [55]:
# slide 233 (2)
# swap two columns (2)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data['b'], data['c']=data['c'].copy(), data['b'].copy()
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  2  1  3  4
1  6  5  7  8
2  8  9  7  6
3  4  5  3  2


In [56]:
# slide 234
# swap two columns (3)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data['b'], data['c']=data['c'], data['b'].copy()
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  2  1  3  4
1  6  5  7  8
2  8  9  7  6
3  4  5  3  2


In [57]:
# slide 235
# swap two columns (?)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data['b'], data['c']=data['c'].copy(), data['b']
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  2  2  3  4
1  6  6  7  8
2  8  8  7  6
3  4  4  3  2


In [58]:
# slide 236
# swap two columns (4)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data[['b','c']]=data[['c','b']] #.copy()
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  2  1  3  4
1  6  5  7  8
2  8  9  7  6
3  4  5  3  2


In [59]:
# slide 237
# swap two columns (5)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data[['b','c']]=data.loc[:,['c','b']] #.copy()
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  2  1  3  4
1  6  5  7  8
2  8  9  7  6
3  4  5  3  2


In [60]:
# slide 238
# Another wrong answer to swap to columns
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.loc[:,['b','c']]=data.loc[:,['c','b']] #.copy()
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


In [61]:
# slide 239
# Another wrong answer to swap to columns
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.loc[:,['b','c']]=data[['c','b']] #.copy()
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


In [62]:
# slide 240
# swap two columns (6)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.loc[:,['b','c']]=data.loc[:,['c','b']].values #.copy()
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  2  1  3  4
1  6  5  7  8
2  8  9  7  6
3  4  5  3  2


In [63]:
# slide 241
# swap two columns (7)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.loc[:,['b','c']]=data[['c','b']].values #.copy()
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  2  1  3  4
1  6  5  7  8
2  8  9  7  6
3  4  5  3  2


In [64]:
# slide 244 (1)
# swap two rows (1)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.loc[[0,1],:]=data.loc[[1,0],:].values #.copy()
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  5  6  7  8
1  1  2  3  4
2  9  8  7  6
3  5  4  3  2


In [65]:
# slide 244 (2)
# swap two rows (2)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.iloc[[0,1],:]=data.iloc[[1,0],:].values #.copy()
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  5  6  7  8
1  1  2  3  4
2  9  8  7  6
3  5  4  3  2


## HT008: Apply a function to each row/column of `data`.

In [66]:
# slide 252
#A Numpy universal function
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.apply(np.sqrt)
#np.sqrt(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


b         c         d         e
a                                        
0  1.000000  1.414214  1.732051  2.000000
1  2.236068  2.449490  2.645751  2.828427
2  3.000000  2.828427  2.645751  2.449490
3  2.236068  2.000000  1.732051  1.414214

In [67]:
# slide 253
#A reducing function, axis=0
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.apply(np.sum,axis=0)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


b    20
c    20
d    20
e    20
dtype: int64

In [68]:
# slide 254
#A reducing function, axis=1
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.apply(np.sum,axis=1)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


a
0    10
1    26
2    30
3    14
dtype: int64

In [69]:
# slide 255
#using a user-defined function, axis=0, return a single number
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.apply(lambda x: x[0]**2+np.sum(x),axis=0)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


b    21
c    24
d    29
e    36
dtype: int64

In [70]:
# slide 256
#using a user-defined function, axis=1, return a list
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.apply(lambda x: [x['d']**2, x['c']**2+np.sum(x)],axis=1)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


a
0     [9, 14]
1    [49, 62]
2    [49, 94]
3     [9, 30]
dtype: object

In [71]:
# slide 257
#using a user-defined function, axis=1, return a list, result_type='expand'
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.apply(lambda x: [x['d']**2, x['c']**2+np.sum(x)], 
                           axis=1, result_type='expand')

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


0   1
a        
0   9  14
1  49  62
2  49  94
3   9  30

In [72]:
# slide 258
#using a user-defined function, axis=1, return a Series
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.apply(lambda x: pd.Series([x['d']**2, x['c']**2+np.sum(x)], 
                               index=['d**2', 'c**2+sum']), 
                               axis=1)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


d**2  c**2+sum
a                
0     9        14
1    49        62
2    49        94
3     9        30

## HT009: Basic operations on two rows/columns of `data`

In [73]:
# slide 270
#DataFrame op row-Series (DataFrame's column labels same as Series' label)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(id(data))
print(data)
print(data.iloc[0,:])
data=data+data.iloc[0,:]
print(id(data))
data

144842536
   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
b    1
c    2
d    3
e    4
Name: 0, dtype: int64
144842144


b   c   d   e
a                
0   2   4   6   8
1   6   8  10  12
2  10  10  10  10
3   6   6   6   6

In [74]:
# slide 271 (1)
#DataFrame op row-Series (DataFrame's column labels same as Series' label)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(id(data))
print(data)
print(data.iloc[0,:])
data.values[:,:]=data+data.iloc[0,:]
print(id(data))
data

144841304
   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
b    1
c    2
d    3
e    4
Name: 0, dtype: int64
144841304


b   c   d   e
a                
0   2   4   6   8
1   6   8  10  12
2  10  10  10  10
3   6   6   6   6

In [75]:
# slide 271 (2)
#assignment: DataFraem->2D array
%reset -f
import pandas as pd
import numpy as np
x=np.ones((3,3))
print(x)
df=pd.DataFrame(np.zeros((3,3)))
print(df)
x[:,:]=df #or df.values
x

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
     0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
# slide 272
#DataFrame op row-Series (DataFrame's column labels same as Series' label)
import pandas as pd
data=pd.read_csv('HT001b.csv', index_col=0, header=0)
print(data)
print(data.iloc[0,:])
data+data.iloc[0,:]

   b  a.1  d e  1
a                
2  1    2    3  4
4  5    6    7  8
3  9    8    7  6
4  5    4    3  2
b      1
a.1    2
d e    3
1      4
Name: 2, dtype: int64


b  a.1  d e   1
a                  
2   2    4    6   8
4   6    8   10  12
3  10   10   10  10
4   6    6    6   6

In [77]:
# slide 273
#DataFrame op 1D array (or list)
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
#arr=range(4)
arr=np.arange(4)
print(arr)
data+arr

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
[0 1 2 3]


b  c  d   e
a             
0  1  3  5   7
1  5  7  9  11
2  9  9  9   9
3  5  5  5   5

In [78]:
# slide 274
#Use one command to add the first column to every column in data
import pandas as pd
import numpy as np
data=pd.read_csv('HT001b.csv', index_col=0, header=0)
print(data)
print('----------------------')
print(id(data))
print('----------------------')
#print(data+data.iloc[:,0]) #Error: cannot reindex
#print(data+data.iloc[:,0].values) #Error: This add the first column to every row
#print(data+data.iloc[:,0].values.reshape(4,1)) #Error: shape must be (4, 4)
print(data+np.tile(data.iloc[:,0].values.reshape(4,1),4))
#print(data+np.tile(data.iloc[:,[0]].values,4))
#print(data.apply(lambda x: x+data.iloc[:,0].values, axis=0))
#
#data=data+np.tile(data.iloc[:,0].values.reshape(4,1),4)
#data=data+np.tile(data.iloc[:,[0]].values,4)
#data=data.apply(lambda x: x+data.iloc[:,0].values, axis=0)
#
#data.values[:,:]=data+np.tile(data.iloc[:,0].values.reshape(4,1),4)
#data.values[:,:]=data+np.tile(data.iloc[:,[0]].values,4)
#data.values[:,:]=data.apply(lambda x: x+data.iloc[:,0].values, axis=0)
print('----------------------')
print(data)
print('----------------------')
print(id(data))

   b  a.1  d e  1
a                
2  1    2    3  4
4  5    6    7  8
3  9    8    7  6
4  5    4    3  2
----------------------
144624552
----------------------
    b  a.1  d e   1
a                  
2   2    3    4   5
4  10   11   12  13
3  18   17   16  15
4  10    9    8   7
----------------------
   b  a.1  d e  1
a                
2  1    2    3  4
4  5    6    7  8
3  9    8    7  6
4  5    4    3  2
----------------------
144624552


In [79]:
# slide 275
#Examples of numpy.tile
import numpy as np
print(np.tile([1,2],2))
print(np.tile([1,2],(2,3)))

[1 2 1 2]
[[1 2 1 2 1 2]
 [1 2 1 2 1 2]]


In [80]:
# slide 277
#Test Numpy Array Arithmetic Operations
import numpy as np
A=[(3,), (3,), (3,4), (3,3), (3,3), (3,4), (3,4), (3,4), (3,4)]
B=[(3,), (4,), (3,4), (3,4), (4,3), (3,1), (1,4), (4,), (3,)]
for i in range(9):
    print("-----", A[i], "+", B[i], "-----")
    array1=np.zeros(A[i])
    array2=np.zeros(B[i])
    try:
        r=array1+array2
    except:
        print("Error.")
    else:
        print(r.shape)

----- (3,) + (3,) -----
(3,)
----- (3,) + (4,) -----
Error.
----- (3, 4) + (3, 4) -----
(3, 4)
----- (3, 3) + (3, 4) -----
Error.
----- (3, 3) + (4, 3) -----
Error.
----- (3, 4) + (3, 1) -----
(3, 4)
----- (3, 4) + (1, 4) -----
(3, 4)
----- (3, 4) + (4,) -----
(3, 4)
----- (3, 4) + (3,) -----
Error.


In [81]:
# slide 278
#What is the output? (DataFrame+1D array)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data.iloc[[0],:])
print(data.iloc[:,3].values)
data.iloc[[0],:]+data.iloc[:,3].values

   b  c  d  e
a            
0  1  2  3  4
[4 8 6 2]


b   c  d  e
a             
0  5  10  9  6

In [82]:
# slide 279
#What is the output? (Series + Series, different labels)
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data.iloc[0,:])
print(data.iloc[:,3])
data.iloc[0,:]+data.iloc[:,3]

b    1
c    2
d    3
e    4
Name: 0, dtype: int64
a
0    4
1    8
2    6
3    2
Name: e, dtype: int64


b   NaN
c   NaN
d   NaN
e   NaN
0   NaN
1   NaN
2   NaN
3   NaN
dtype: float64

In [83]:
# slide 280
# How to calculate ...
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
print(data.iloc[1:,[0]])
print(data.iloc[:-1,1].values)
#data.iloc[1:,[0]]+data.iloc[:-1,1].values.reshape(3,1)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b
a   
1  5
2  9
3  5
[2 6 8]


In [84]:
# slide 281 (1)
A=np.array([[1,2,3]])
B=np.array([[1],[2],[3]])
A@B

array([[14]])

In [85]:
# slide 281 (2)
A=np.array([1,2,3])
B=np.array([1,2,3])
A@B

14

In [86]:
# slide 282
# Use one command to compute the matrix multiplication, 
# using the first 3 rows in data as the first matrix, 
# and using the last row (without finding the number of 
# rows) as the second 1-column matrix.
import pandas as pd
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
data.values[:3] @ data.values[-1]
#data.values[:3] @ data.values[-1:].T
#data.values[:3] @ data.values[[-1]].T

array([ 30,  86, 110], dtype=int64)

## HT010: Sort `data`

In [87]:
# slide 290
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
print(data.sort_values(by='b',axis=0))
print(data.sort_values(by=['b','c'],axis=0))
print(np.sort(data,axis=0))
print(data)
data.values.sort(axis=0)
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
3  5  4  3  2
2  9  8  7  6
   b  c  d  e
a            
0  1  2  3  4
3  5  4  3  2
1  5  6  7  8
2  9  8  7  6
[[1 2 3 2]
 [5 4 3 4]
 [5 6 7 6]
 [9 8 7 8]]
   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  1  2  3  2
1  5  4  3  4
2  5  6  7  6
3  9  8  7  8


In [88]:
# slide 291 (1)
#Use one command with pandas.DataFrame.sort_values
#to sort data using the 3rd row
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
print(id(data))
data.sort_values(by=data.index[2],axis=1,inplace=True)
print(data)
print(id(data))

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
144621920
   e  d  c  b
a            
0  4  3  2  1
1  8  7  6  5
2  6  7  8  9
3  2  3  4  5
144621920


In [89]:
# slide 291 (2)
#Use one command with pandas.DataFrame.sort_values
#to sort data using the 3rd column
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
print(id(data))
data.sort_values(by=data.columns[2],axis=0,inplace=True)
print(data)
print(id(data))

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
144625168
   b  c  d  e
a            
0  1  2  3  4
3  5  4  3  2
1  5  6  7  8
2  9  8  7  6
144625168


In [90]:
# slide 292 (1)
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
I=np.argsort(data.values,axis=0)
print(I)
print(data.values[I[:,2],:])
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
[[0 0 0 3]
 [1 3 3 0]
 [3 1 1 2]
 [2 2 2 1]]
[[1 2 3 4]
 [5 4 3 2]
 [5 6 7 8]
 [9 8 7 6]]
   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


In [91]:
# slide 292 (2)
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
I=np.argsort(data.values,axis=1)
print(I)
print(data.values[:,I[2,:]])
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
[[0 1 2 3]
 [0 1 2 3]
 [3 2 1 0]
 [3 2 1 0]]
[[4 3 2 1]
 [8 7 6 5]
 [6 7 8 9]
 [2 3 4 5]]
   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2


In [92]:
#Use one command to sort data using the 3rd column
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.values[:,:]=data.values[np.argsort(data.values,axis=0)[:,2],:]
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  1  2  3  4
1  5  4  3  2
2  5  6  7  8
3  9  8  7  6


In [93]:
#Use one command to sort data using the 3rd row
import pandas as pd
import numpy as np
data=pd.read_csv('HT001a.csv', index_col=0, header=0)
print(data)
data.values[:,:]=data.values[:,np.argsort(data.values,axis=1)[2,:]]
print(data)

   b  c  d  e
a            
0  1  2  3  4
1  5  6  7  8
2  9  8  7  6
3  5  4  3  2
   b  c  d  e
a            
0  4  3  2  1
1  8  7  6  5
2  6  7  8  9
3  2  3  4  5


## Caution: Numpy Arrays

In [94]:
# slide 303 (1)
import numpy as np
x=np.arange(1,10).reshape(3,3)
print(x)
x[1,:]=x[:,2]
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [3 9 9]
 [7 8 9]]


In [95]:
# slide 303 (2)
import numpy as np
x=np.arange(1,10).reshape(3,3)
print(x)
x[1,:]=x[:,2].copy()
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [3 6 9]
 [7 8 9]]


In [96]:
# slide 304 (1)
import numpy as np
x=np.arange(1,10).reshape(3,3)
print(x)
x[:,1]=x[2,:]
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 7 3]
 [4 8 6]
 [7 9 9]]


In [97]:
# slide 304 (2)
import numpy as np
x=np.arange(1,10).reshape(3,3)
print(x)
x[:,1]=x[2,:].copy()
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 7 3]
 [4 8 6]
 [7 9 9]]


In [98]:
# slide 305
import numpy as np
print(np.arange(100).reshape(10,10))
for i in range(10):
    print('*'*10+" ","x[%d,:]=x[:,8]" % i," "+"*"*10)
    x=np.arange(100).reshape(10,10)
    x[i,:]=x[:,8]
    print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
**********  x[0,:]=x[:,8]  **********
[[ 8 18 28 38 48 58 68 78 88 98]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
**********  x[1,:]=x[:,8]  **********
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 8 88 28 38 48 58 68 78 88 98]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79