In [255]:
import numpy as np
import pandas as pd
x = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])

In [274]:
x[:2][:1]

array([[0, 1, 2]])

In [148]:
(np.cumsum([[1, 2, 3, 4],[1, 2, 3, 4]])).shape

(8,)

In [193]:
np.logical_or(False, [True, False, False])

array([ True, False, False])

In [115]:
b = x[:2]
print(b)
a = x[[2]]
print(a)
x[:2] = 0
print(b)
print(a)

[[0 1 2]
 [3 4 5]]
[[6 7 8]]
[[0 0 0]
 [0 0 0]]
[[6 7 8]]


In [171]:
y = pd.DataFrame(np.arange(16).reshape(4, 4), index=[2, 1, 4, 3], columns=list('bcad'));y

b   c   a   d
2   0   1   2   3
1   4   5   6   7
4   8   9  10  11
3  12  13  14  15

In [177]:
asdf = y['b']

In [181]:
asdf[[True, True, True, False]]

2    0
1    4
4    8
Name: b, dtype: int32

In [314]:
p = pd.DataFrame([1, 2, 3])
q = pd.DataFrame([[1, 2, 3]])
p
p['f3'] = np.arange(3)
p['f3']=np.arange(3).reshape(3,1)
print(p)
p.loc['100', :] = 1
p = p.append(pd.DataFrame(1, columns=p.columns, index =[120]))
p = p.append(pd.DataFrame(np.arange(1, 3).reshape(1, 2), columns=p.columns, index =[130]))
print(p)
p.sum(axis=0)

   0  f3
0  1   0
1  2   1
2  3   2
       0   f3
0    1.0  0.0
1    2.0  1.0
2    3.0  2.0
100  1.0  1.0
120  1.0  1.0
130  1.0  2.0


0     9.0
f3    7.0
dtype: float64

In [100]:
k =[1, 2, 3, 4]
k[0:] = [5, 6, 7, 8]
k

[5, 6, 7, 8]

In [117]:
print(np.any([[True, False], [True, False]]))
print(np.any([[True, False], [True, False]], axis=0))
print(np.any([[True, False], [True, False]], axis=1))
print(np.any([[True, False], [True, False]], axis=-1))

True
[ True False]
[ True  True]
[ True  True]


In [151]:
np.random.randn(3, 4)

array([[-1.47527337, -0.07913656, -1.44871004,  0.99640151],
       [ 0.90100379,  0.6927456 , -1.30092806,  0.58862751],
       [ 0.1861804 , -1.62407999,  1.0564414 , -1.48348942]])

In [152]:
np.random.standard_normal((3, 4))

array([[ 0.15336938,  1.20586614, -0.64914386, -0.4981253 ],
       [ 1.56728153, -0.18028664,  0.42325705,  0.68004085],
       [ 0.99716763, -0.28345904, -0.61112042,  0.00813524]])

In [156]:
np.random.random((3, 4))

array([[0.27920722, 0.93121123, 0.07688363, 0.66842804],
       [0.790001  , 0.17999441, 0.59483051, 0.70734603],
       [0.71262291, 0.93362931, 0.63751928, 0.12419451]])

In [157]:
np.random.rand(3, 4)

array([[0.52412721, 0.05063864, 0.7847629 , 0.85833676],
       [0.61952614, 0.83886427, 0.16191368, 0.75616722],
       [0.52389797, 0.23187073, 0.55289022, 0.02440539]])

In [159]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
np.append([[1, 2, 3], [4, 5, 6]], [[7], [8]], axis=1)

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [194]:
import matplotlib.pyplot as plt
fig, ax = plt.subplots()

In [196]:
x=[0,2,0,0,3,3,1, 3]
y1=[1,4,4,5,5,4,1, 1]
list(zip(x, y1))

[(0, 1), (2, 4), (0, 4), (0, 5), (3, 5), (3, 4), (1, 1), (3, 1)]

In [201]:
np.ndarray.reshape(np.array([1, 2, 3, 4, 5, 6]), (3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [207]:
np.all([[True, False]], axis=0)

array([ True, False])

In [221]:
yyy = np.array([1, 2, 3, 4, 5])
yyy[[True, True, False, False, False]]

array([1, 2])

In [226]:
np.linspace(0, 20, 10, endpoint = False)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [225]:
np.linspace(0, 20, 10, endpoint = True)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [227]:
o = pd.Series(range(5))

In [234]:
o[:3] - o[2:].values

0   -2
1   -2
2   -2
dtype: int64

In [242]:
np.random.seed(0)
np.random.randn(1)

array([1.76405235])

In [237]:
np.random.standard_normal((1,))

array([0.18271043])

In [241]:
np.random.seed(0)
np.random.randn(1)

array([1.76405235])

In [252]:
N =3
fc = [[0.0 for j in range(i+1)] for i in range(N+1)]
print(fc)
print(fc[1])

for j in range(N+1):
    fc[N][j] = max(0, np.random.standard_normal((1,))[0])
    
fc

[[0.0], [0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
[0.0, 0.0]


[[0.0],
 [0.0, 0.0],
 [0.0, 0.0, 0.0],
 [0, 0.04575851730144607, 0, 1.5327792143584575]]

In [254]:
fp = [0]*(N+1); fp

[0, 0, 0, 0]

In [281]:
n = pd.DataFrame([1, 2, 3])
m = pd.DataFrame([[1, 2, 3]])
print(n)
print(m)
n.values+m.values

   0
0  1
1  2
2  3
   0  1  2
0  1  2  3


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]], dtype=int64)